version = 0.1

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "dev-spvadv-stack-km"
s3_bucket = "dev-kmspvadv-s3-bucket-eu-central-1-deploy-artifact"
s3_prefix = "dev-spvadv-stack-km"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "STAGE=\"dev\" PROJECT=\"spvadv\""


[poc]
[poc.deploy]
[poc.deploy.parameters]
stack_name = "poc-spvadv-stack-km"
s3_bucket = "poc-kmspvadv-s3-deploy-artifact"
s3_prefix = "poc-spvadv-stack-km"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "STAGE=\"poc\" PROJECT=\"spvadv\""


[stg]
[stg.deploy]
[stg.deploy.parameters]
stack_name = "stg-spvadv-stack"
s3_bucket = "stg-spvadv-s3-deploy-artifact"
s3_prefix = "stg-spvadv-stack"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "STAGE=\"stg\" PROJECT=\"spvadv\""


[prd]
[prd.deploy]
[prd.deploy.parameters]
stack_name = "prd-spvadv-stack"
s3_bucket = "prd-spvadv-s3-deploy-artifact"
s3_prefix = "prd-spvadv-stack"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "STAGE=\"prd\" PROJECT=\"spvadv\""


[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dev-spvadv-stack-km"
s3_bucket = "dev-spvadv-s3-deploy-artifact"
s3_prefix = "dev-spvadv-stack-km"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "STAGE=\"dev\" PROJECT=\"spvadv\""
