DROP TABLE IF EXISTS spvadv.t_user_vehicle CASCADE;
CREATE TABLE spvadv.t_user_vehicle (
  user_vehicle_id serial NOT NULL,
  gigya_uid varchar(50) NOT NULL,
  vehicle_id varchar(14) NOT NULL,
  peripheral_identifier varchar(255),
  complete_local_name varchar(255),
  managed_flag boolean DEFAULT false NOT NULL,
  registered_flag boolean DEFAULT false NOT NULL,
  unit_no varchar(12),
  frame_no varchar(14),
  model_code char(4) NOT NULL,
  vehicle_name varchar(255),
  fcdyobi1 varchar(10),
  fcdyobi2 varchar(10),
  fcdyobi3 varchar(10),
  fcdyobi4 varchar(10),
  fcdyobi5 varchar(10),
  etxyobi1 varchar(50),
  etxyobi2 varchar(50),
  etxyobi3 varchar(50),
  etxyobi4 varchar(50),
  etxyobi5 varchar(50),
  delete_flag boolean DEFAULT false,
  delete_timestamp timestamp(3) without time zone,
  delete_user_id varchar(50),
  insert_timestamp timestamp(3) without time zone,
  insert_user_id varchar(50),
  update_timestamp timestamp(3) without time zone,
  update_user_id varchar(50),
  PRIMARY KEY (user_vehicle_id),
  UNIQUE(gigya_uid, vehicle_id),
  FOREIGN KEY (model_code) REFERENCES spvadv.m_model(model_code)
);
CREATE INDEX ON spvadv.t_user_vehicle(gigya_uid);