DROP TABLE IF EXISTS spvadv.t_maintain_history;
CREATE TABLE spvadv.t_maintain_history (
  maintain_history_id bigserial NOT NULL,
  gigya_uid varchar(50) NOT NULL,
  user_vehicle_id int NOT NULL,
  maintain_item_code char(5) NOT NULL,
  model_code char(4) NOT NULL,
  maintain_implement_date timestamp(3) without time zone NOT NULL,
  maintain_location varchar(255),
  maintain_cost int,
  maintain_required_time int,
  maintain_memo text,
  maintain_du_serial_number varchar(50) NOT NULL,
  maintain_du_last_timestamp timestamp(3)without time zone  NOT NULL,
  maintain_du_last_odometer int NOT NULL,
  maintain_image_ids text,
  fcdyobi1 varchar(10),
  fcdyobi2 varchar(10),
  fcdyobi3 varchar(10),
  fcdyobi4 varchar(10),
  fcdyobi5 varchar(10),
  etxyobi1 varchar(50),
  etxyobi2 varchar(50),
  etxyobi3 varchar(50),
  etxyobi4 varchar(50),
  etxyobi5 varchar(50),
  delete_flag boolean DEFAULT false,
  delete_timestamp timestamp(3) without time zone,
  delete_user_id varchar(50),
  insert_timestamp timestamp(3) without time zone,
  insert_user_id varchar(50),
  update_timestamp timestamp(3) without time zone,
  update_user_id varchar(50),
  PRIMARY KEY (maintain_history_id),
  UNIQUE(gigya_uid, user_vehicle_id, maintain_item_code, maintain_implement_date),
  FOREIGN KEY (user_vehicle_id) REFERENCES spvadv.t_user_vehicle(user_vehicle_id),
  FOREIGN KEY (maintain_item_code, model_code) REFERENCES spvadv.m_maintain_item(maintain_item_code, model_code)
);
CREATE INDEX ON spvadv.t_maintain_history(gigya_uid, user_vehicle_id);
CREATE INDEX ON spvadv.t_maintain_history(user_vehicle_id, maintain_implement_date);
