DROP TABLE IF EXISTS spvadv.t_ride_track;
DROP TABLE IF EXISTS spvadv.t_ride_history;
CREATE TABLE spvadv.t_ride_history (
  ride_history_id varchar(50) NOT NULL,
  gigya_uid varchar(50) NOT NULL,
  user_vehicle_id int NOT NULL,
  start_timestamp timestamp(3) without time zone NOT NULL,
  end_timestamp timestamp(3) without time zone,
  ride_name varchar(50) NOT NULL,
  trip_distance real NOT NULL,
  trip_time bigint NOT NULL,
  total_calorie int NOT NULL,
  battery_consumption int NOT NULL,
  average_speed int NOT NULL,
  max_speed int NOT NULL,
  max_pedaling_power int NOT NULL,
  max_cadence int NOT NULL,
  bookmark_flg boolean DEFAULT false NOT NULL,
  fcdyobi1 varchar(10),
  fcdyobi2 varchar(10),
  fcdyobi3 varchar(10),
  fcdyobi4 varchar(10),
  fcdyobi5 varchar(10),
  etxyobi1 varchar(50),
  etxyobi2 varchar(50),
  etxyobi3 varchar(50),
  etxyobi4 varchar(50),
  etxyobi5 varchar(50),
  delete_flag boolean DEFAULT false,
  delete_timestamp timestamp(3) without time zone,
  delete_user_id varchar(50),
  insert_timestamp timestamp(3) without time zone,
  insert_user_id varchar(50),
  update_timestamp timestamp(3) without time zone,
  update_user_id varchar(50),
  PRIMARY KEY (ride_history_id),
  UNIQUE(gigya_uid, user_vehicle_id, start_timestamp),
  FOREIGN KEY (user_vehicle_id) REFERENCES spvadv.t_user_vehicle(user_vehicle_id)
);
CREATE INDEX ON spvadv.t_ride_history(gigya_uid);