DROP TABLE IF EXISTS spvadv.t_user_setting_ride;
CREATE TABLE spvadv.t_user_setting_ride (
  gigya_uid varchar(50) NOT NULL,
  battery_remind_latitude double precision DEFAULT NULL,
  battery_remind_longitude double precision DEFAULT NULL,
  battery_remind_cd char(2) DEFAULT '00',
  battery_remind_voice_notice boolean DEFAULT false,
  safety_ride_alert boolean DEFAULT true,
  long_drive_alert boolean DEFAULT true,
  speed_over_alert boolean DEFAULT true,
  no_light_alert boolean DEFAULT false,
  safety_ride_voice_notice boolean DEFAULT true,
  home_assist_mode_number char(2) DEFAULT '02',
  fcdyobi1 varchar(10),
  fcdyobi2 varchar(10),
  fcdyobi3 varchar(10),
  fcdyobi4 varchar(10),
  fcdyobi5 varchar(10),
  etxyobi1 varchar(50),
  etxyobi2 varchar(50),
  etxyobi3 varchar(50),
  etxyobi4 varchar(50),
  etxyobi5 varchar(50),
  delete_flag boolean DEFAULT false,
  delete_timestamp timestamp(3) without time zone,
  delete_user_id varchar(50),
  insert_timestamp timestamp(3) without time zone,
  insert_user_id varchar(50),
  update_timestamp timestamp(3) without time zone,
  update_user_id varchar(50),
  PRIMARY KEY (gigya_uid)
);
