DROP TABLE IF EXISTS spvadv.t_route CASCADE;
CREATE TABLE spvadv.t_route (
  route_id bigserial NOT NULL,
  gigya_uid varchar(50) NOT NULL,
  user_vehicle_id int NOT NULL,
  save_timestamp timestamp(3) without time zone,
  origin_name varchar(255),
  origin_location geometry(POINT, 4326),
  origin_place_id text,
  destination_name varchar(255),
  destination_location geometry(POINT, 4326),
  destination_place_id text,
  ride_date date,
  weather char(3),
  weather_icon char(3),
  fcdyobi1 varchar(10),
  fcdyobi2 varchar(10),
  fcdyobi3 varchar(10),
  fcdyobi4 varchar(10),
  fcdyobi5 varchar(10),
  etxyobi1 varchar(50),
  etxyobi2 varchar(50),
  etxyobi3 varchar(50),
  etxyobi4 varchar(50),
  etxyobi5 varchar(50),
  delete_flag boolean DEFAULT false,
  delete_timestamp timestamp(3) without time zone,
  delete_user_id varchar(50),
  insert_timestamp timestamp(3) without time zone,
  insert_user_id varchar(50),
  update_timestamp timestamp(3) without time zone,
  update_user_id varchar(50),
  PRIMARY KEY (route_id),
  FOREIGN KEY (user_vehicle_id) REFERENCES spvadv.t_user_vehicle(user_vehicle_id)
);
