DROP TABLE IF EXISTS spvadv.t_route_one_way;
CREATE TABLE spvadv.t_route_one_way (
  route_id bigint NOT NULL,
  route_one_way_id bigserial NOT NULL,
  round_trip_type_code char(2),
  duration int,
  distance int,
  route_type char(2),
  route_type_branch_no int,
  fcdyobi1 varchar(10),
  fcdyobi2 varchar(10),
  fcdyobi3 varchar(10),
  fcdyobi4 varchar(10),
  fcdyobi5 varchar(10),
  etxyobi1 varchar(50),
  etxyobi2 varchar(50),
  etxyobi3 varchar(50),
  etxyobi4 varchar(50),
  etxyobi5 varchar(50),
  delete_flag boolean DEFAULT false,
  delete_timestamp timestamp(3) without time zone,
  delete_user_id varchar(50),
  insert_timestamp timestamp(3) without time zone,
  insert_user_id varchar(50),
  update_timestamp timestamp(3) without time zone,
  update_user_id varchar(50),
  PRIMARY KEY (route_id, route_one_way_id),
  FOREIGN KEY (route_id) REFERENCES spvadv.t_route(route_id)
);
