DROP TABLE IF EXISTS spvadv.t_route_via_point;
CREATE TABLE spvadv.t_route_via_point (
  route_id bigint NOT NULL,
  route_one_way_id bigint NOT NULL,
  route_via_point_id bigserial NOT NULL,
  route_via_point_location geometry(POINT, 4326),
  route_via_point_place_id text,
  route_via_point_type char(2) DEFAULT NULL,
  fcdyobi1 varchar(10),
  fcdyobi2 varchar(10),
  fcdyobi3 varchar(10),
  fcdyobi4 varchar(10),
  fcdyobi5 varchar(10),
  etxyobi1 varchar(50),
  etxyobi2 varchar(50),
  etxyobi3 varchar(50),
  etxyobi4 varchar(50),
  etxyobi5 varchar(50),
  delete_flag boolean DEFAULT false,
  delete_timestamp timestamp(3) without time zone,
  delete_user_id varchar(50),
  insert_timestamp timestamp(3) without time zone,
  insert_user_id varchar(50),
  update_timestamp timestamp(3) without time zone,
  update_user_id varchar(50),
  PRIMARY KEY (route_id, route_one_way_id, route_via_point_id),
  FOREIGN KEY (route_id, route_one_way_id) REFERENCES spvadv.t_route_one_way(route_id, route_one_way_id)
);
