DROP TABLE IF EXISTS spvadv.t_bicycle_parking;
CREATE TABLE spvadv.t_bicycle_parking (
  route_id bigint NOT NULL,
  bicycle_parking_id bigserial NOT NULL,
  bicycle_parking_name varchar(255),
  bicycle_parking_distance int,
  bicycle_parking_location geometry(POINT, 4326),
  bicycle_parking_place_id text,
  fcdyobi1 varchar(10),
  fcdyobi2 varchar(10),
  fcdyobi3 varchar(10),
  fcdyobi4 varchar(10),
  fcdyobi5 varchar(10),
  etxyobi1 varchar(50),
  etxyobi2 varchar(50),
  etxyobi3 varchar(50),
  etxyobi4 varchar(50),
  etxyobi5 varchar(50),
  delete_flag boolean DEFAULT false,
  delete_timestamp timestamp(3) without time zone,
  delete_user_id varchar(50),
  insert_timestamp timestamp(3) without time zone,
  insert_user_id varchar(50),
  update_timestamp timestamp(3) without time zone,
  update_user_id varchar(50),
  PRIMARY KEY (route_id, bicycle_parking_id),
  FOREIGN KEY (route_id) REFERENCES spvadv.t_route(route_id)
);
