DROP TABLE IF EXISTS spvadv.t_workout;
CREATE TABLE spvadv.t_workout (
  workout_id bigserial NOT NULL,
  data_source_kind_code char(2),
  data_source_id varchar(50),
  gigya_uid varchar(50),
  user_vehicle_id int,
  start_timestamp timestamp(3),
  end_timestamp timestamp(3),
  workout_time bigint,
  trip_distance real,
  total_calorie real,
  heartbeat_zone_1_time bigint,
  heartbeat_zone_2_time bigint,
  heartbeat_zone_3_time bigint,
  heartbeat_zone_4_time bigint,
  heartbeat_zone_5_time bigint,
  average_heart_rate real,
  average_speed real,
  max_speed real,
  average_pedaling_power real,
  max_pedaling_power real,
  average_cadence real,
  max_cadence real,
  weather char(3),
  temperature real,
  humidity int,
  workout_mode_code char(2),
  fcdyobi1 varchar(10),
  fcdyobi2 varchar(10),
  fcdyobi3 varchar(10),
  fcdyobi4 varchar(10),
  fcdyobi5 varchar(10),
  etxyobi1 varchar(50),
  etxyobi2 varchar(50),
  etxyobi3 varchar(50),
  etxyobi4 varchar(50),
  etxyobi5 varchar(50),
  delete_flag boolean DEFAULT false,
  delete_timestamp timestamp(3) without time zone,
  delete_user_id varchar(50),
  insert_timestamp timestamp(3) without time zone,
  insert_user_id varchar(50),
  update_timestamp timestamp(3) without time zone,
  update_user_id varchar(50),
  PRIMARY KEY (workout_id),
  FOREIGN KEY (user_vehicle_id) REFERENCES spvadv.t_user_vehicle(user_vehicle_id),
  CONSTRAINT unique_data_source UNIQUE(data_source_kind_code, data_source_id)
);
