name: Run CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Setting variable(case main)
      #   if: ${{ github.ref_name == 'main'}}
      #   run: |
      #     echo 'STAGE=poc' >> $GITHUB_ENV
      #     echo 'REGION=eu-west-1' >> $GITHUB_ENV
      #     echo 'ROLE_ARN=arn:aws:iam::850854818590:role/poc-spvadv-github-actions-role' >> $GITHUB_ENV

      # - name: Setting variable(case develop)
      #   if: ${{ github.ref_name == 'develop'}}
      #   run: |
      #     echo 'STAGE=dev' >> $GITHUB_ENV
      #     echo 'REGION=eu-central-1' >> $GITHUB_ENV
      #     echo 'ROLE_ARN=arn:aws:iam::850854818590:role/dev-spvadv-github-actions-role' >> $GITHUB_ENV

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.9'

      # - name: Setup SAM
      #   uses: aws-actions/setup-sam@v2

      # - name: Setup credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     role-to-assume: ${{ env.ROLE_ARN }}
      #     aws-region: ${{ env.REGION }}

      # - name: Build and deploy SAM application
      #   run: |
      #     cd backend/
      #     sam build --config-env ${{ env.STAGE }}
      #     sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env ${{ env.STAGE }}