name: Run CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setting variable(case main)
        if: ${{ github.base_ref == 'main'}}
        run: |
          echo 'REGION=eu-west-1' >> $GITHUB_ENV

      - name: Setting variable(case develop)
        if: ${{ github.base_ref == 'develop'}}
        run: |
          echo 'REGION=eu-central-1' >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd ./backend/
          pip install pipenv
          pipenv install --dev
          sudo apt-get update -y
          sudo apt-get install -y software-properties-common wget
          sudo add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main"
          wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update -y
          sudo apt-get install -y postgresql-14 postgresql-client-14

      - name: Run lint
        run: |
          cd ./backend/
          pipenv run lint

      - name: Run unit tests
        run: |
          cd ./backend/
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
          export AWS_DEFAULT_REGION=${{ env.REGION }}
          echo 'REGION is set to:'
          echo ${{ env.REGION }}
          pipenv run ut